services:
  postgres:
    image: postgres:15-alpine
    container_name: mindscribe-db
    environment:
      - POSTGRES_USER=luiz
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mindscribe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: